### ISSUE TITLE
Animations wont start

### ISSUE THREAD

**Issue by davidhringur** [maustinstar/shiny#4]
I am trying to get this to work, but the animation wont start for the first example when I import to my project? The title just turns red and nothing happens.

Does this package not work anymore?

**Comment by artur-marchetto** [comment]
yeah I don't think they're supporting the library anymore.. maybe copy some code and get it to work on your project!

**Comment by maustinstar** [comment]
Are you running this on a device that has a gyroscope? (i.e. not the simulator)

**Comment by davidhringur** [comment]
You are correct, I did not realize that the effects are contingent on the gyroscope, should have read the discription more thoroughly. Thanks!
