### ISSUE TITLE
Disables touch gestures for items in ForEach loop

### ISSUE THREAD

**Issue by liamcharger** [maustinstar/shiny#9]
I have a list of items using ForEach and ScrollView, and if I use _shiny_ on one of the items, the whole view stops receiving touch gestures correctly for every view except the last one. For example, if I add a button to the view, the button won't click, and if I add a _contextMenu_ to the items, it opens a context for the item at the bottom of the list.

**Comment by Onnwen** [comment]
> I have a list of items using ForEach and ScrollView, and if I use _shiny_ on one of the items, the whole view stops receiving touch gestures correctly for every view except the last one. For example, if I add a button to the view, the button won't click, and if I add a _contextMenu_ to the items, it opens a context for the item at the bottom of the list.

Adding `.allowsHitTesting(false)` after the `.shiny()` modifier seem to solve the issue.

**Comment by liamcharger** [comment]
That fixed it!
